lesson1/assignments/andrysetiawan/config/routes.rb
Rails.application.routes.draw do
  resources :enquiries
  resources :properties
  devise_for :users
  get 'dashboards/index'

  root to: 'dashboards#index'
end

lesson1/assignments/andrysetiawan/app/models/enquiry.rb
class Enquiry < ApplicationRecord
  belongs_to :property
  belongs_to :customer, foreign_key: :user_id
  has_many :messages
  accepts_nested_attributes_for :customer, :reject_if => :all_blank

  # after_save :send_message
  before_save :set_booking_info

  validates_presence_of [
    :checkin,
    :checkout,
    :number_of_adults,
    :number_of_children,
    :number_of_infants
  ]

  def nights
    (checkout.to_date - checkin.to_date).to_i if checkin? && checkout?
  end

  def fist_message
    self.messages.first
  end


  def set_booking_info
    self.reference_number = SecureRandom.hex(4).upcase
    self.total_cost = self.property.cost * self.nights
    self.currency = self.property.currency
    self.tax = self.property.tax * self.nights
  end

  def send_message
    self.messages.create(
      from: Enquiry::FROM,
      to: self.customer.email,
      subject: "[#{self.reference_number}] Enquiry for #{self.property}",
      message_at: Time.now,
      body: self.enquiry_message
    )
  end

  def enquiry_message
    "
      Hello #{self.customer}\n\n
      Thanks For Your Enquiry\n
      Checkin: #{self.checkin}\n
      Checkout: #{self.checkout}\n
      Guest: \n
      -Adult: #{self.number_of_adults}\n
      -Child: #{self.number_of_children}\n
      -Infant: #{self.number_of_infants}\n
    "
  end
end

lesson1/assignments/andrysetiawan/app/controllers/enquiries_controller.rb
class EnquiriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_enquiry, only: [:show, :edit, :update, :destroy]

  # GET /enquiries
  # GET /enquiries.json
  def index
    @enquiries = Enquiry.all
  end

  # GET /enquiries/1
  # GET /enquiries/1.json
  def show
  end

  # GET /enquiries/new
  def new
    @enquiry = Enquiry.new(number_of_adults: 2, number_of_children: 0, number_of_infants: 0)
    @enquiry.build_customer
  end

  # GET /enquiries/1/edit
  def edit
  end

  # POST /enquiries
  # POST /enquiries.json
  def create
    @enquiry = Enquiry.new(enquiry_params)
    generated_password = Devise.friendly_token.first(8)
    @enquiry.customer.password = generated_password if @enquiry.customer.password.blank?
    respond_to do |format|
      if @enquiry.save
        format.html { redirect_to @enquiry, notice: 'Enquiry was successfully created.' }
        format.json { render :show, status: :created, location: @enquiry }
      else
        format.html { render :new }
        format.json { render json: @enquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enquiries/1
  # PATCH/PUT /enquiries/1.json
  def update
    respond_to do |format|
      if @enquiry.update(enquiry_params)
        format.html { redirect_to @enquiry, notice: 'Enquiry was successfully updated.' }
        format.json { render :show, status: :ok, location: @enquiry }
      else
        format.html { render :edit }
        format.json { render json: @enquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enquiries/1
  # DELETE /enquiries/1.json
  def destroy
    @enquiry.destroy
    respond_to do |format|
      format.html { redirect_to enquiries_url, notice: 'Enquiry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enquiry
      @enquiry = Enquiry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enquiry_params
      #  params.require(:enquiry).permit(:property_id, :checkin, :checkout, :number_of_adults, :number_of_children, :number_of_infants, :user_id,
      #   customer_attributes: [:full_name, :email,:id, :_destroy])
      params.require(:enquiry).permit(:property_id, :checkin, :checkout, :number_of_adults, :number_of_children, :number_of_infants, :user_id)
    end
end

lesson1/assignments/andrysetiawan/app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

lesson1/assignments/andrysetiawan/app/views/enquiries/_enquiry.html.erb
  <div class="row message">
  <div class="col-md-2"><%= truncate(enquiry.customer.to_s, length: 20) %> <span class="badge badge-default">Enquiry</span></div>
  <div class="col-md-3"><%= enquiry.checkin.to_date %> to <%= enquiry.checkout.to_date %><br/><%= enquiry.property %></div>
  <div class="col-md-3"><%= "#{enquiry.currency} #{number_to_currency(enquiry.total_cost)}" %></div>
  <div class="col-md-2">
    <%= time_ago_in_words(enquiry.created_at) unless enquiry.created_at.blank? %>

  </div>
  <div class="col-md-1"><span class="badge badge-default"><%= enquiry.messages.count %></span></div>
  <div class="col-md-1"><%= link_to "Show", enquiry_path(enquiry), class: 'card-link' %></div>
</div>

lesson1/assignments/andrysetiawan/app/views/enquiries/_form.html.erb
<%= form_with(model: enquiry, local: true) do |form| %>
  <% if enquiry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enquiry.errors.count, "error") %> prohibited this enquiry from being saved:</h2>

      <ul>
      <% enquiry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :property_id %>
    <%= form.collection_select(:property_id, Property.all, :id, :name , {}, {class: 'form-control'}) %>
  </div>

  <div class="field">
    <%= form.label :checkin %>
    <%= form.text_field :checkin, id: :enquiry_checkin, class: "datepicker form-control" %>
  </div>

  <div class="field">
    <%= form.label :checkout %>
    <%= form.text_field :checkout, id: :enquiry_checkout, class: "datepicker form-control" %>
  </div>

  <div class="field">
    <%= form.label :number_of_adults %>
    <%= form.number_field :number_of_adults, id: :enquiry_number_of_adults %>
  </div>

  <div class="field">
    <%= form.label :number_of_children %>
    <%= form.number_field :number_of_children, id: :enquiry_number_of_children %>
  </div>

  <div class="field">
    <%= form.label :number_of_infants %>
    <%= form.number_field :number_of_infants, id: :enquiry_number_of_infants %>
  </div>

  <div class="field">
    <%= form.label :user_id, "Contact / Customer" %>
    <%#= form.text_field :user_id, id: :enquiry_user_id %>
    <%= form.fields_for :customer do |us| %>
      <%= us.hidden_field :id%>
      <%= us.text_field :full_name, placeholder: "Full Name" %>
      <%= us.text_field :email, placeholder: "Email" %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

lesson1/assignments/andrysetiawan/app/views/enquiries/edit.html.erb
<h1>Editing Enquiry</h1>

<%= render 'form', enquiry: @enquiry %>

<%= link_to 'Show', @enquiry %> |
<%= link_to 'Back', enquiries_path %>

lesson1/assignments/andrysetiawan/app/views/enquiries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enquiries</h1>

<table>
  <thead>
    <tr>
      <th>Property</th>
      <th>Checkin</th>
      <th>Checkout</th>
      <th>Number of adults</th>
      <th>Number of children</th>
      <th>Number of infants</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enquiries.each do |enquiry| %>
      <tr>
        <td><%= enquiry.property %></td>
        <td><%= enquiry.checkin %></td>
        <td><%= enquiry.checkout %></td>
        <td><%= enquiry.number_of_adults %></td>
        <td><%= enquiry.number_of_children %></td>
        <td><%= enquiry.number_of_infants %></td>
        <td><%= enquiry.customer %></td>
        <td><%= link_to 'Show', enquiry %></td>
        <td><%= link_to 'Edit', edit_enquiry_path(enquiry) %></td>
        <td><%= link_to 'Destroy', enquiry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enquiry', new_enquiry_path %>

lesson1/assignments/andrysetiawan/app/views/enquiries/new.html.erb
<h1>New Enquiry</h1>

<%= render 'form', enquiry: @enquiry %>

<%= link_to 'Back', enquiries_path %>

lesson1/assignments/andrysetiawan/app/views/enquiries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Property:</strong>
  <%= @enquiry.property %>
</p>

<p>
  <strong>Checkin:</strong>
  <%= @enquiry.checkin %>
</p>

<p>
  <strong>Checkout:</strong>
  <%= @enquiry.checkout %>
</p>

<p>
  <strong>Number of adults:</strong>
  <%= @enquiry.number_of_adults %>
</p>

<p>
  <strong>Number of children:</strong>
  <%= @enquiry.number_of_children %>
</p>

<p>
  <strong>Number of infants:</strong>
  <%= @enquiry.number_of_infants %>
</p>

<p>
  <strong>Costss:</strong>
  <%= "#{@enquiry.currency} #{@enquiry.total_cost}" %>
</p>

<p>
  <strong>Tax:</strong>
  <%= "#{@enquiry.currency} #{@enquiry.tax}" %>
</p>

<p>
  <strong>Contact/Customer:</strong>
  <%= @enquiry.customer %>
</p>

<%= link_to 'Edit', edit_enquiry_path(@enquiry) %> |
<%= link_to 'Back', enquiries_path %>