lesson1/assignments/andrysetiawan/config/routes.rb
Rails.application.routes.draw do
  resources :enquiries
  resources :properties
  devise_for :users
  get 'dashboards/index'

  root to: 'dashboards#index'
end

lesson1/assignments/andrysetiawan/app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  has_many :enquiries
  validates :name, uniqueness: true, presence: true
  def to_s
    self.name
  end
end

lesson1/assignments/andrysetiawan/app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_property, only: [:show, :edit, :update, :destroy]
  before_action :set_users, only: [:edit, :new, :create, :update]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    def set_users
      @users = User.all.map{|x| [x.full_name, x.id]}
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:name, :description, :address, :searchable, :cost, :tax, :currency, :user_id)
    end
end

lesson1/assignments/andrysetiawan/app/helpers/properties_helper.rb
module PropertiesHelper
end

lesson1/assignments/andrysetiawan/app/views/properties/_form.html.erb
<%= form_with(model: property, local: true) do |form| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :property_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :property_description %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :property_address %>
  </div>

  <div class="field">
    <%= form.label :searchable %>
    <%= form.check_box :searchable, id: :property_searchable %>
  </div>

  <div class="field">
    <%= form.label :cost %>
    <%= form.text_field :cost, id: :property_cost %>
  </div>

  <div class="field">
    <%= form.label :tax %>
    <%= form.text_field :tax, id: :property_tax %>
  </div>

  <div class="field">
    <%= form.label :currency %>
    <%= form.text_field :currency, id: :property_currency %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.select :user_id, Partner.all.map{|x| [x.full_name, x.id]} %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

lesson1/assignments/andrysetiawan/app/views/properties/_property.html.erb
<div class="col-sm-6 col-md-4 col-lg-3 mt-4">
<div class="card" >

<!-- Heading -->
<div class="card-block">
<h4 class="card-title"><%= property.name %></h4>
<h6 class="card-subtitle text-muted"><%= "#{number_to_currency(property.cost, unit: property.currency, precision: 0)}" %></h6>
</div>

<!-- Image -->
<img src="https://d2w31iprc6cx5g.cloudfront.net/luxelet/data/45100/small_dsc7418.jpg" alt="Photo of sunset">

<!-- Text Content -->
<div class="card-block">
<p class="card-text"><%= truncate(property.description, length: 200) %></p>
<%= link_to "Show", property_path(property), class: 'card-link' %>
<%= link_to "Destroy", property_path(property), class: 'card-link', method: :delete %>
<%= link_to "Edit", edit_property_path(property), class: 'card-link' %>
</div>
</div>
</div>

lesson1/assignments/andrysetiawan/app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

lesson1/assignments/andrysetiawan/app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Properties</h1>

<div class="row">

    <% @properties.each do |property| %>
      <%= render property %>
    <% end %>
</div>

<br>

<%= link_to 'New Property', new_property_path %>

lesson1/assignments/andrysetiawan/app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

lesson1/assignments/andrysetiawan/app/views/properties/show.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <div class="carousel-inner" role="listbox">
    <div class="item">
      <img class="first-slide" src="https://d2w31iprc6cx5g.cloudfront.net/luxelet/data/45100/xlarge_dsc7418.jpg" alt="First slide">
    </div>
  </div>
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<div class="row">
  <div class="col-8 col-sm-8 blog-main">
    <div class="blog-post">
      <h2 class="blog-post-title"><%= @property.name %></h2>
      <p class="blog-post-meta"><%= @property.updated_at.strftime('%B %d, %Y') %> by <a href="#"><%= @property.user%></a></p>

      <p><%= @property.description %></p>
    </div>
  </div>

  <div class="col-4">

    <div class="card" >

    <!-- Heading -->
    <div class="card-block">
      <h6 class="card-title">Price From </h3>
      <hr>
      <h3 class="card-subtitle text-muted">
        <%= "#{number_to_currency(@property.cost, unit: @property.currency, precision: 0)}" %>
      </h3>
      <span>per Night </span>
      <p>Including tax & service fees</p>
      <div class="form-group row">
        <div class="col-4">
          <input type="text" class="date datepicker form-control" placeholder="checkin">
        </div>
        <div class="col-4">
          <input type="text" class="date datepicker form-control" placeholder="checkout">
        </div>
        <div class="col-4">
          <input type="text" class="form-control" placeholder="guest">
        </div>
      </div>
      <div class="row">
        <div class="col-12">
          <button type="button" class="btn btn-primary">Booking</button>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-12">
          <strong>Inclusions:</strong>
          <span class="card-title">Breakfast, Housekeeping daily, Purified drinking water, Grocery shopping and butler service, 24x7 security guards, Welcome drink, cool towel, fruit basket upon arrival</span>
        </div>
      </div>
    </div>
  </div>

  </div>

</div>